// Core authentication services
export { AuthService, authService, createAuthService } from './auth-service'
export { RBACService, rbacService, ROLES, PERMISSIONS, PERMISSION_CONSTANTS } from './rbac'
export { SessionService, sessionService, createSessionService, DEFAULT_SESSION_CONFIG } from './session'

// React context and hooks
export { 
  AuthProvider, 
  useAuth, 
  useIsAuthenticated, 
  useCurrentUser, 
  useAuthLoading, 
  useAuthError,
  usePermissions,
  useHasPermission,
  useHasRole,
  useHasAnyRole,
  useHasAllRoles,
  useCanAccess,
  useSession,
  useIsSessionValid,
  withAuth,
  withRole,
  withPermission
} from './auth-context'

// Additional hooks
export {
  useUser,
  usePermissions as usePermissionsHook,
  useSession as useSessionHook,
  useIsAuthenticated as useIsAuthenticatedHook,
  useAuthLoading as useAuthLoadingHook,
  useAuthError as useAuthErrorHook,
  useHasPermission as useHasPermissionHook,
  useHasRole as useHasRoleHook,
  useHasAnyRole as useHasAnyRoleHook,
  useHasAllRoles as useHasAllRolesHook,
  useCanAccess as useCanAccessHook,
  useCurrentSession,
  useIsSessionValid as useIsSessionValidHook,
  useSessionTimeRemaining,
  useIsSessionExpiringSoon,
  useUserRoleLevel,
  useHasRoleLevel,
  useEffectivePermissions,
  useValidatePermissions,
  useRoleHierarchy,
  useCanPerformAction,
  useUserDisplayName,
  useUserInitials,
  useUserAvatar,
  useUserDepartment,
  useUserRoles,
  useUserGroups,
  useIsUserActive,
  useUserLastLogin,
  useUserLastActivity,
  useIsInGroup,
  useIsInAnyGroup,
  useIsInAllGroups,
  usePrimaryRole,
  useRoleLabel,
  useRoleColor,
  useIsAdmin,
  useIsLabManager,
  useIsProjectManager,
  useIsPaletteManager,
  useIsPerfumer,
  useCanManageUsers,
  useCanManagePerfumes,
  useCanManageFormulas,
  useCanManageProjects,
  useCanManageCases,
  useCanManageIngredients,
  useCanManageReports,
  useCanAccessSystemAdmin,
  useCanAccessSystemSettings,
  useCanViewSystemLogs,
  useAuthStatus,
  useUserProfile,
  usePermissionSummary
} from './hooks'

// Utilities
export {
  validateEmail,
  validatePassword,
  validateCredentials,
  generateSecureToken,
  hashPassword,
  verifyPassword,
  sanitizeInput,
  isTokenExpired,
  isTokenExpiringSoon,
  formatTokenExpiry,
  createAuthError,
  AUTH_ERROR_CODES,
  createCommonAuthErrors,
  isAuthError,
  formatAuthError,
  getUserInitials,
  getUserDisplayName,
  hasPermission,
  hasRole,
  hasAnyRole,
  hasAllRoles,
  canAccess,
  debounce,
  throttle,
  generateCSRFToken,
  validateCSRFToken,
  isBrowser,
  isServer,
  getClientIP,
  getUserAgent,
  isMobile,
  isTablet,
  isDesktop,
  formatFileSize,
  validateFileType,
  validateFileSize,
  createFormData,
  parseApiError,
  retryWithBackoff,
  withTimeout,
  safeJsonParse,
  safeJsonStringify
} from './utils'

// Types
export type {
  AuthState,
  User,
  Permission,
  Role,
  Session,
  AuthCredentials,
  AuthResponse,
  LoginFormState,
  UserProfileUpdate,
  PasswordChange,
  AuthContextType,
  PermissionCheck,
  RouteProtection,
  ComponentProtection,
  AuthError,
  SessionTimeoutConfig,
  AuthConfig,
  UserActivityEvent,
  UseAuthReturn,
  UseUserReturn,
  UsePermissionsReturn,
  UseSessionReturn,
  UserRole,
  PermissionAction,
  PermissionResource,
  AuthEventType,
  AuthEvent,
  AuthMiddlewareContext,
  ProtectedRouteProps,
  RoleGuardProps,
  PermissionGuardProps,
  AuthStatusProps,
  UserProfileProps,
  LoginFormProps,
  LogoutButtonProps
} from './types'

// Re-export from API auth for compatibility
export type { TokenData, UserInfo } from '@/lib/api/auth'
