import type { Meta, StoryObj } from '@storybook/react'
import { IngredientList } from './ingredient-list'
import { Ingredient, IngredientSearchParams } from '@/types/ingredient'

const meta: Meta<typeof IngredientList> = {
  title: 'Components/Ingredients/IngredientList',
  component: IngredientList,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
  argTypes: {
    onSearch: { action: 'search' },
    onFilter: { action: 'filter' },
    onPageChange: { action: 'pageChange' },
    onPageSizeChange: { action: 'pageSizeChange' },
    onRefresh: { action: 'refresh' },
    onView: { action: 'view' },
    onEdit: { action: 'edit' },
    onDelete: { action: 'delete' },
    onUpdateStock: { action: 'updateStock' },
    onCreate: { action: 'create' },
    onImport: { action: 'import' },
    onExport: { action: 'export' },
    onBulkAction: { action: 'bulkAction' },
    onSelectionChange: { action: 'selectionChange' },
    onViewModeChange: { action: 'viewModeChange' },
    showFilters: { control: 'boolean' },
    showSearch: { control: 'boolean' },
    showActions: { control: 'boolean' },
    compact: { control: 'boolean' },
  },
}

export default meta
type Story = StoryObj<typeof meta>

// Sample ingredients data
const sampleIngredients: Ingredient[] = [
  {
    id: '1',
    name: 'Lavender Essential Oil',
    type: 'essential_oil',
    category: 'top_notes',
    supplier: 'Essential Oils Co.',
    supplierCode: 'EO-LAV-001',
    cost: 25.50,
    currency: 'USD',
    stockLevel: 1000,
    minStockLevel: 100,
    maxStockLevel: 2000,
    unit: 'ml',
    casNumber: '8000-28-0',
    inciName: 'Lavandula Angustifolia Oil',
    description: 'High-quality lavender essential oil with calming properties',
    notes: 'Store in cool, dark place',
    tags: ['floral', 'calming', 'natural'],
    isActive: true,
    createdBy: 'user123',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: '2',
    name: 'Rose Absolute',
    type: 'natural_extract',
    category: 'middle_notes',
    supplier: 'Premium Extracts Ltd.',
    supplierCode: 'PE-ROS-002',
    cost: 150.00,
    currency: 'USD',
    stockLevel: 50,
    minStockLevel: 100,
    maxStockLevel: 500,
    unit: 'g',
    casNumber: '8000-28-0',
    inciName: 'Rosa Damascena Absolute',
    description: 'Premium rose absolute from Bulgaria',
    notes: 'Handle with care, very concentrated',
    tags: ['floral', 'luxury', 'rose'],
    isActive: true,
    createdBy: 'user123',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-18T16:45:00Z',
  },
  {
    id: '3',
    name: 'Sandalwood Essential Oil',
    type: 'essential_oil',
    category: 'base_notes',
    supplier: 'Exotic Oils Inc.',
    supplierCode: 'EO-SAN-003',
    cost: 200.00,
    currency: 'USD',
    stockLevel: 0,
    minStockLevel: 50,
    maxStockLevel: 200,
    unit: 'ml',
    casNumber: '8006-87-9',
    inciName: 'Santalum Album Oil',
    description: 'Rare sandalwood essential oil from India',
    notes: 'Out of stock - reorder needed',
    tags: ['woody', 'luxury', 'rare'],
    isActive: true,
    createdBy: 'user123',
    createdAt: '2024-01-05T11:30:00Z',
    updatedAt: '2024-01-25T10:15:00Z',
  },
  {
    id: '4',
    name: 'Methyl Anthranilate',
    type: 'synthetic',
    category: 'middle_notes',
    supplier: 'Chemical Solutions Co.',
    supplierCode: 'CS-MA-004',
    cost: 12.50,
    currency: 'USD',
    stockLevel: 2000,
    minStockLevel: 500,
    maxStockLevel: 5000,
    unit: 'g',
    casNumber: '134-20-3',
    inciName: 'Methyl Anthranilate',
    description: 'Synthetic grape-like fragrance compound',
    notes: 'Stable synthetic compound',
    tags: ['synthetic', 'grape', 'fruity'],
    isActive: true,
    createdBy: 'user123',
    createdAt: '2024-01-12T14:20:00Z',
    updatedAt: '2024-01-22T08:30:00Z',
  },
  {
    id: '5',
    name: 'Benzoin Resin',
    type: 'fixative',
    category: 'base_notes',
    supplier: 'Natural Resins Ltd.',
    supplierCode: 'NR-BR-005',
    cost: 45.00,
    currency: 'USD',
    stockLevel: 300,
    minStockLevel: 100,
    maxStockLevel: 1000,
    unit: 'g',
    casNumber: '9000-05-9',
    inciName: 'Styrax Benzoin Resin',
    description: 'Natural benzoin resin for fixative properties',
    notes: 'Excellent fixative for perfumes',
    tags: ['fixative', 'resin', 'warm'],
    isActive: true,
    createdBy: 'user123',
    createdAt: '2024-01-08T13:45:00Z',
    updatedAt: '2024-01-19T12:00:00Z',
  },
  {
    id: '6',
    name: 'Ethanol 96%',
    type: 'solvent',
    category: 'solvents',
    supplier: 'Solvent Solutions Inc.',
    supplierCode: 'SS-ET-006',
    cost: 8.00,
    currency: 'USD',
    stockLevel: 5000,
    minStockLevel: 1000,
    maxStockLevel: 10000,
    unit: 'l',
    casNumber: '64-17-5',
    inciName: 'Alcohol',
    description: 'High-purity ethanol for fragrance dilution',
    notes: 'Handle with care - flammable',
    tags: ['solvent', 'alcohol', 'dilution'],
    isActive: true,
    createdBy: 'user123',
    createdAt: '2024-01-03T16:10:00Z',
    updatedAt: '2024-01-21T09:45:00Z',
  },
]

export const Default: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const Loading: Story = {
  args: {
    ingredients: [],
    loading: true,
    error: null,
    totalCount: 0,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const Error: Story = {
  args: {
    ingredients: [],
    loading: false,
    error: 'Failed to load ingredients. Please try again.',
    totalCount: 0,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const Empty: Story = {
  args: {
    ingredients: [],
    loading: false,
    error: null,
    totalCount: 0,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const ListView: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'list',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const Compact: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: true,
  },
}

export const WithSelection: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: ['1', '2', '3'],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const NoFilters: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: false,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const NoSearch: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: false,
    showActions: true,
    compact: false,
  },
}

export const NoActions: Story = {
  args: {
    ingredients: sampleIngredients,
    loading: false,
    error: null,
    totalCount: 6,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: false,
    compact: false,
  },
}

export const LargeDataset: Story = {
  args: {
    ingredients: Array.from({ length: 50 }, (_, i) => ({
      ...sampleIngredients[i % sampleIngredients.length],
      id: `ingredient-${i + 1}`,
      name: `Ingredient ${i + 1}`,
    })),
    loading: false,
    error: null,
    totalCount: 50,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const Pagination: Story = {
  args: {
    ingredients: sampleIngredients.slice(0, 3),
    loading: false,
    error: null,
    totalCount: 25,
    currentPage: 2,
    pageSize: 3,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const OnlyEssentialOils: Story = {
  args: {
    ingredients: sampleIngredients.filter(ingredient => ingredient.type === 'essential_oil'),
    loading: false,
    error: null,
    totalCount: 3,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}

export const LowStockOnly: Story = {
  args: {
    ingredients: sampleIngredients.filter(ingredient => 
      ingredient.stockLevel <= ingredient.minStockLevel
    ),
    loading: false,
    error: null,
    totalCount: 2,
    currentPage: 1,
    pageSize: 20,
    selectedIngredients: [],
    viewMode: 'grid',
    showFilters: true,
    showSearch: true,
    showActions: true,
    compact: false,
  },
}
