#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to check and fix staged files
npx lint-staged

# Run fast unit tests for changed files
npm run test:unit -- --bail --findRelatedTests

# Run accessibility tests for changed files
npm run test:a11y -- --bail --findRelatedTests
